ROCm/builder

common/install_rocm_magma.sh, libtorch/Dockerfile
build_manylinux_image.sh failing with error:
```
#63 [rocm_final  7/10] RUN bash ./install_rocm_magma.sh && rm install_rocm_magma.sh
#63 sha256:f92e89921615840c390212d4d9246862670d672114ffe61a2eeee7d45c3deda6
#63 0.598 + MKLROOT=/opt/intel
#63 0.598 + apt-get install -y python
#63 0.600 ./install_rocm_magma.sh: line 12: apt-get: command not found
#63 ERROR: executor failed running [/bin/sh -c bash ./install_rocm_magma.sh && rm install_rocm_magma.sh]: exit code: 127
------
> [rocm_final  7/10] RUN bash ./install_rocm_magma.sh && rm install_rocm_magma.sh:
------
executor failed running [/bin/sh -c bash ./install_rocm_magma.sh && rm install_rocm_magma.sh]: exit code: 127
```
python installation is needed when building magma from source for ROCm (not needed for CUDA because CUDA wheel build …
=> Move python install to libtorch/Dockerfile

common/install_miopen.sh
Background: https://ontrack-internal.amd.com/browse/SWDEV-356492
Verified that PyTorch wheels generated using this fix do not throw any errors when running pytorch-micro-benchmarking on gfx908.
Wheels with MLIR disabled generated in CI job: http://rocmhead.amd.com:8080/job/pytorch/job/manylinux_rocm_wheels/144/
=> Disable MLIR backend when building MIOpen

common/install_miopen.sh
Using `-eq` instead of `-ge` seems more appropriate since we don't intend to use older MIOpen branches for newer ROCm releases anyway.
=> Use ROCm5.3 branch for MIOpen

common/install_miopen.sh
Certain tuning updates were put into the staging branch: https://github.com/ROCmSoftwarePlatform/MIOpen/compare/release/rocm-rel-5.3...release/rocm-rel-5.3-staging
=> Use staging branch of MIOpen for ROCm5.3

common/install_miopen.sh
This corrects a mistake in the previous update where we imposed strict equality for ROCm releases: https://github.com/ROCmSoftwarePlatform/builder/pull/12
This breaks for minor ROCm releases.
The original intent was to ensure we don't use stale MIOpen branches for newer ROCm major releases.
=> Allow ROCm minor releases to use the same MIOpen branch as the major release

manywheel/build_common.sh, manywheel/build_libtorch.sh, manywheel/build_rocm.sh
=> Refactor wheel and libtorch build scripts

manywheel/build_rocm.sh
Tested bash logic for correctness locally.
=> rocfft/hipfft link to libhiprtc.so in ROCm5.4

manywheel/Dockerfile, manywheel/build_rocm.sh
Avoid rebuilding MIOpen from source for PyTorch wheels, and instead use the MIOpen .so that comes with the ROCm release. Bundle the .db files in the wheel instead of embedding them into the MIOpen .so. 
BONUS: This should enable file I/O for the MIOpen .so, which can then read .kdb files if they're placed in the correct path (ie. ../share (wrt the location of the libMIOpen.so) by the user. Just to clarify, we will NOT bundle the .kdb files with the wheels due to their large size, so the user will need to manually install them and place them in the correct path above (we could provide the user a helper script for the same purpose).
FUTURE TODO:
1. Helper script to install the .kdb files in the correct location for the wheels.
2. Builder script to install miopen binaries from a non-standard …
=> Disable MIOpen build from source for PyTorch wheels

manywheel/build_common.sh, manywheel/build_libtorch.sh, manywheel/build_rocm.sh
The PR moves to use libtinfo.so.6 on ROCm5.3 and beyond and includes a logic fix in build_common.sh and build_libtorch.sh
https://github.com/pytorch/pytorch/actions/runs/3957589701/jobs/6778142096
https://github.com/pytorch/pytorch/pull/92538
This fixes the error message seen for ROCm5.3 eg. in https://ossci-raw-job-status.s3.amazonaws.com/log/10656518264: 
```
2023-01-15T10:02:53.3817808Z + g++ /builder/test_example_code/simple-torch-test.cpp -I/tmp/libtorch/include -I/tmp/libtorch/include/torch/csrc/api/include -D_GLIBCXX_USE_CXX11_ABI=1 -std=gnu++14 -L/tmp/libtorch/lib -Wl,-R/tmp/libtorch/lib -Wl,--no-as-needed -ltorch -ltorch_cpu -lc10 -o simple-torch-test
2023-01-15T10:03:08.1787744Z /usr/bin/ld: /tmp/libtorch/lib/libamd_comgr.so: undefined reference to …
```
=> libtinfo.so version update and logic fix

common/install_conda.sh
We require the same fix that was made on upstream pytorch https://github.com/pytorch/pytorch/pull/91371
https://github.com/ROCmSoftwarePlatform/pytorch/commit/b72ec7cfbfa7e985986c4ac7e35bd486ffe5e212
Without this change install_conda.sh stage fails
```
#21 6.254 CondaFileIOError: '/opt/conda/pkgs/envs/*/env.txt'. [Errno 2] No such file or directory: '/opt/conda/pkgs/envs/*/env.txt'
#21 6.254 
#21 ERROR: executor failed running [/bin/sh -c bash ./install_conda.sh && rm install_conda.sh]: exit code: 1
------
> [conda 2/3] RUN bash ./install_conda.sh && rm install_conda.sh:
------
executor failed running [/bin/sh -c bash ./install_conda.sh && rm install_conda.sh]: exit code: 1
```
Locally tested with the `/builder/libtorch/build_docker.sh`
=> Fix conda install on distributions with strict POSIX sh

manywheel/Dockerfile
Upstream is on 3.18.4
Build break seen when building pytorch 1.13 wheels - http://rocm-ci.amd.com/view/Release-5.4/job/pytorch_manylinux_libtorch_wheels_rel-5.4/27/console
=> Update cmake version 3.18.4

manywheel/build_rocm.sh
Tested successfully in http://rocmhead:8080/job/pytorch/job/dev/job/manylinux_rocm_wheels/112. Wheels produced and microbenchmarking ran successfully.
=> Conditionalise librocfft-device so's out of rocm5.5

manywheel/build_rocm.sh
Redirect error message to stderr and throw exit 1 if a library cannot be found.
=> Exit on missing file in build_rocm.sh

common/install_rocm_miopen_rpm.sh
Companion PR to https://github.com/ROCmSoftwarePlatform/rocAutomation/pull/114
Adds new `common/install_rocm_miopen_rpm.sh` file which will install a given MIOpen rpm package from a given source. 
`export MIOPEN_RPM_SOURCE=https://repo.radeon.com/rocm/yum/5.4/main/miopen-hip-2.19.0.50400-72.el7.x86_64.rpm`
**build_wheel.sh**
In build_wheel.sh we have deployed an approach related to the MIOpen install approach from upstream https://github.com/pytorch/builder/blob/main/common/install_miopen.sh#L134
1. wget the ${MIOPEN_RPM_SOURCE} and throw an error if the download fails
```
+ docker exec -t manylinux-rocm-py3.8 bash -c 'source /env && bash /builder/common/install_rocm_miopen_rpm.sh'
Running on Linux 89640942d125 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 …
```
=> Add miopen install rpm script

common/install_patchelf.sh
https://github.com/pytorch/builder/commit/18c5017d9eedd2e5e203608e9ad6c05a2324b3ac since tip-of-tree patchelf repo was exhibiting the following error for various libraries in wheel build jobs:
"ELF load command address/offset not properly aligned"
=> Cherry-pick patch for patchelf from upstream

manywheel/build_rocm.sh
Verified successfully via: http://rocmhead.amd.com:8080/job/pytorch/job/dev/job/manylinux_rocm_wheels/228/
Relevant snippet
```
[2023-06-12T16:02:56.679Z] ++ srcpath=/opt/rocm/lib/msccl-algorithms/allreduce-allpairs-16n-16tb.xml
[2023-06-12T16:02:56.679Z] ++ dstpath=torch/lib/msccl-algorithms/allreduce-allpairs-16n-16tb.xml
[2023-06-12T16:02:56.679Z] +++ dirname torch/lib/msccl-algorithms/allreduce-allpairs-16n-16tb.xml
[2023-06-12T16:02:56.679Z] ++ mkdir -p torch/lib/msccl-algorithms
[2023-06-12T16:02:56.679Z] ++ cp /opt/rocm/lib/msccl-algorithms/allreduce-allpairs-16n-16tb.xml torch/lib/msccl-algorithms/allreduce-allpairs-16n-16tb.xml
```
=> [SWDEV-404135] Add msccl-algorithms directory to PyTorch wheel

manywheel/build_rocm.sh
Fix erroneous logic that was skipping msccl files even for ROCm5.6; update msccl path for ROCm5.7
Tested via http://rocmhead.amd.com:8080/job/pytorch/job/dev/job/manylinux_rocm_wheels/242/
```
[2023-08-04T08:36:36.228Z] ++ srcpath=/opt/rocm/lib/msccl-algorithms/allreduce-allpairs-16n-16tb.xml
[2023-08-04T08:36:36.228Z] ++ dstpath=torch/lib/msccl-algorithms/allreduce-allpairs-16n-16tb.xml
[2023-08-04T08:36:36.228Z] +++ dirname torch/lib/msccl-algorithms/allreduce-allpairs-16n-16tb.xml
[2023-08-04T08:36:36.228Z] ++ mkdir -p torch/lib/msccl-algorithms
[2023-08-04T08:36:36.228Z] ++ cp /opt/rocm/lib/msccl-algorithms/allreduce-allpairs-16n-16tb.xml torch/lib/msccl-algorithms/allreduce-allpairs-16n-16tb.xml
[2023-08-04T08:36:36.228Z] ++ (( ++i ))
[2023-08-04T08:36:36.228Z] ++ (( i<1086 )) …
```
=> Fix msccl-algorithms logic for ROCm5.6 and ROCm5.7

manywheel/build_rocm.sh
Tested successfully using wheels generated from: http://rocmhead.amd.com:8080/job/pytorch/job/dev/job/manylinux_rocm_wheels/241/
Successfully set RPATH for libs in wheel:
```
jenkins@f789cee5d847:/data$ pip install --force-reinstall torch-2.1.0.dev20230803+rocm5.6-cp38-cp38-linux_x86_64.whl
Processing ./torch-2.1.0.dev20230803+rocm5.6-cp38-cp38-linux_x86_64.whl
...
Successfully installed MarkupSafe-2.1.3 filelock-3.12.2 fsspec-2023.6.0 jinja2-3.1.2 mpmath-1.3.0 networkx-3.1 sympy-1.12 torch-2.1.0.dev20230803+rocm5.6 typing-extensions-4.7.1
jenkins@f789cee5d847:/data$ echo $LD_LIBRARY_PATH
...
jenkins@f789cee5d847:/data$ cd /opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/lib
jenkins@f789cee5d847:/opt/conda/envs/py_3.8/lib/python3.8/site-packages/torch/lib$ readelf -a …
```
=> Set FORCE_RPATH for ROCm

manywheel/Dockerfile
Recent ROCm6.0 mainline builds (eg. build 12887) do NOT need this workaround to find HIP.
=> Remove ROCM_PATH env workaround

manywheel/Dockerfile
This is done as a workaround for - https://ontrack-internal.amd.com/browse/SWDEV-429841
=> Adding back setting of ROCM_PATH env

manywheel/Dockerfile
- Choosing 3.22.0 since binary is available in pypi
- Docker image use 3.24.6 to switch to this version needs to be built from source, leading to installing many dependencies.
- enable_language(HIP) support is required, which is added after 3.21 https://cmake.org/cmake/help/v3.21/command/enable_language.html, which is currently used in tensorpipe and fbgemm-gpu.
=> CMake version updated to 3.22.0

manywheel/build_rocm.sh
* Reinstate PyTorch dependency on hashed version of triton (essentially reverts https://github.com/ROCm/builder/commit/e72594460667b62dfef87b582d46c324d9719da9): Tested successfully via http://rocm-ci.amd.com/job/rocm-pytorch-manylinux-wheel-builder/154
* Do not add triton dependency for PyTorch versions older than 1.13: Tested successfully via http://rocm-ci.amd.com/job/rocm-pytorch-manylinux-wheel-builder/155
=> [rocm6.1] Update Triton dependency logic

manywheel/build_rocm.sh
Tested via: 
PyTorch2.1: http://rocm-ci.amd.com/job/rocm-pytorch-manylinux-wheel-builder/162
PyTorch2.0: http://rocm-ci.amd.com/job/rocm-pytorch-manylinux-wheel-builder/163
=> [rocm6.1] Add ROCM_VERSION to triton dependency

.github/scripts/validate_binaries.sh, common/install_miopen.sh, common/install_rocm.sh, common/install_rocm_drm.sh, common/install_rocm_magma.sh, manywheel/Dockerfile, manywheel/Dockerfile_2_28, manywheel/build_common.sh, manywheel/build_docker.sh, manywheel/build_rocm.sh
* Add manylinux2_28 case to `manywheel/build_docker.sh`
* Update steps to install libraries such as magma for ROCm
* Clean up old-ROCm-version code
* Use _GLIBCXX_USE_CXX11_ABI=1: https://github.com/ROCm/builder/pull/51/commits/9daa4e4b540b7c39c82b8d60b45d93b866dd7241
* Install numpy<2.0.0 for PyTorch versions<2.4: https://github.com/ROCm/builder/pull/51/commits/6bf4bfd163f3810f6e2d016145fde94dca688527
* Add conditions for ROCm6.2 and ROCm6.3 in `common/install_miopen.sh`
* Upgrade CMake version to 3.28.4 (need minimum of 3.21 to get `enable_langugage(HIP)` support, but 3.21 has a bug that inserts dynamic linker flags `-Wl,no-as-needed` in static linker flags causing build failure)
* Skip unnecessary installation of epel rpm from expired link for CentOS7
* Install epel-release-7 from …
=> Changes to enable manylinux2_28 wheels for ROCm

common/install_miopen.sh
... until [MIOpen fix for std::filesystem issue](https://github.com/ROCm/MIOpen/pull/3126) makes it to ROCm6.3 mainline by applying patch from https://github.com/ROCm/MIOpen/commit/f6c993171cb0a96ebcc220f84cb1b5b234bbae0f
Tested via: http://ml-ci-internal.amd.com:8080/blue/organizations/jenkins/pytorch%2Fdev%2Fmanylinux_rocm_wheels_test/detail/manylinux_rocm_wheels_test/166
=> Re-enable MIOpen build from source for ROCm6.3 mainline

manywheel/build_rocm.sh
Fixes wheel build errors due to updated hipsolver dependencies since build ~14586 eg. http://rocm-ci.amd.com/job/rocm-pytorch-manylinux-wheel-builder/564/console
```
cp: cannot stat '/lib64/libsuitesparseconfig.so.4': No such file or directory
```
Tested via py3.9 branch of: http://rocm-ci.amd.com/job/rocm-pytorch-manylinux-wheel-builder/569/
=> [rocm6.3] Update library dependencies for hipsolver

manywheel/build_common.sh, wheel/build_wheel.sh
Removed pip install -quiet for better build debug info.
=> [rocm6.2] Wheel build remove quiet pip

manywheel/build_rocm.sh
Validation: http://rocm-ci.amd.com/job/mainline-pytorch2.5-manylinux-wheels/25/
=> [rocm6.3_pytorch_2.4] Enable pytorch 2.5 wheels

manywheel/Dockerfile_2_28
Add in setuptools and wheel package in the dockerfile because they are not included in 3.12 onwards
Related to https://github.com/ROCm/rocAutomation/pull/593
Validation:
http://ml-ci-internal.amd.com:8080/job/pytorch/job/dev/job/lightweight_wheels_test/297/
=> Enable py3.13 wheels 

manywheel/build_rocm.sh
conditionalize and python_version < '3.13'" only for PyTorch 2.5 and older
Tested via: http://ml-ci-internal.amd.com:8080/job/pytorch/job/manylinux_rocm_wheels/541/
```
[2025-02-13T16:14:17.115Z] + export 'PYTORCH_EXTRA_INSTALL_REQUIREMENTS=pytorch-triton-rocm==3.2.0+rocm6.3.2.git6da9e660; platform_system == '\''Linux'\'' and platform_machine == '\''x86_64'\'''
```
=> [rocm6.3] Update triton requirements and conditionalize python_version < '3.13' only for PyTorch <= 2.5

manywheel/build_common.sh, manywheel/build_rocm.sh, manywheel/build_torch_wheel.sh
Highlights:
* `LIGHTWEIGHT_WHEELNAME_MARKER` env var passed in from rocAutomation `build_wheel.sh` (part of https://github.com/ROCm/rocAutomation/pull/759)
* `do_lightweight_build` sets `WHEELNAME_MARKER` env var to `LIGHTWEIGHT_WHEELNAME_MARKER`, whereas `do_heavyweight_build` sets it to empty string
* `build_torch_wheel.sh` will only build one (lightweight) pytorch wheel, but without modifying the `build_version` (so that `torch` package doesn't self-report version as `.lw`)
* `build_torch_wheel.sh` copies the lightweight wheel into an `.lw` subdirectory (makes it easy to pick up lw/hw wheel exclusively in the `build_common.sh` logic:
`for pkg in /$WHEELHOUSE_DIR/torch_no_python*.whl /$WHEELHOUSE_DIR/${WHEELNAME_MARKER}/torch*linux*.whl /$LIBTORCH_HOUSE_DIR/libtorch*.zip; do`
* …
=> Additional changes to make heavyweight + lightweight wheel generation work

manywheel/build_rocm.sh
Failure
http://rocm-ci.amd.com/job/rocm-pytorch-manylinux-wheel-builder/1970/parameters/
Basically bash internally tries to parse 002008000000 as an octal literal (because of the leading 0). But octal only allows digits 0–7, so the 8 in 008 is invalid. To fix this we strip the leading zero (so bash treats it as decimal)
```
[2025-05-08T11:27:34.899Z] ++ printf %03d%03d%03d%03d 2 5
[2025-05-08T11:27:34.899Z] + [[ 002008000000 -ge 002005000000 ]]
[2025-05-08T11:27:34.899Z] /builder/manywheel/build_rocm.sh: line 346: [[: 002008000000: value too great for base (error token is "002008000000")
[2025-05-08T11:27:34.899Z] ++ cut -c1-8 /pytorch/.ci/docker/ci_commit_pins/triton-rocm.txt
[2025-05-08T11:27:34.899Z] cut: /pytorch/.ci/docker/ci_commit_pins/triton-rocm.txt: No such file or directory …
```
=> [main] Fix 2.8

common/install_rocm_magma.sh
Fixes errors such as:
```
14:59:22  [0m[91msrc/xhsgetrf_gpu.cpp:403:21: error: no matching function for call to 'hipblasGemmEx'
14:59:22    403 |                     hipblasGemmEx( queues[1]->hipblas_handle(),
14:59:22        |                     ^~~~~~~~~~~~~
14:59:22  [0m[91m/opt/rocm-7.0.0/lib/llvm/bin/../../../include/hipblas/hipblas.h:31119:32: note: candidate function not viable: no known conversion from 'hipDataType' to 'hipblasDatatype_t' for 9th argument
```
when building Magma.
=> [add_rocroller] Update magma install instructions for ROCm7.0 (#80)

manywheel/Dockerfile_2_28, manywheel/build_docker.sh
* Use newer devtoolset11 to sync with upstream: https://github.com/pytorch/pytorch/pull/141609
* Use devtoolset 11
* Set LDFLAGS and DEVTOOLSET_VERSION
(cherry picked from commit a80f1effed2da6b951b935587da40601ee412707)
Relates to: https://github.com/ROCm/rocAutomation/pull/937
Validation: 
* 2.7: http://rocm-ci.amd.com/job/pytorch-pipeline-manylinux-wheel-builder_rel-6.4/379/
* 2.5: http://rocm-ci.amd.com/job/pytorch-pipeline-manylinux-wheel-builder_rel-6.4/400/
=> [rocm6.4] devtoolset / GCC11 upgrade on manylinux images

manywheel/build_rocm.sh
hipblasLT dependency on rocroller has made it into mainline as of build 16233 at least, as evidenced by
http://rocm-ci.amd.com/blue/organizations/jenkins/rocm-pytorch-manylinux-wheel-builder/detail/rocm-pytorch-manylinux-wheel-builder/2914/pipeline/143
=> Add rocroller lib to pytorch wheel dependencies

manywheel/build_rocm.sh
relates to https://github.com/ROCm/pytorch/pull/2518
Release 7.0: http://rocm-ci.amd.com/job/pytorch2.6-manylinux-wheels_rel-7.0/40/
`pytorch_triton_rocm-3.2.0+rocm7.0.0.git20943800-cp313-cp313-linux_x86_64.whl pushed to http://compute-artifactory.amd.com/artifactory/compute-pytorch-rocm/compute-rocm-rel-7.0/6/triton_main_conditionalize/pytorch_triton_rocm-3.2.0+rocm7.0.0.git20943800-cp313-cp313-linux_x86_64.whl`
Mainline: http://rocm-ci.amd.com/job/mainline-pytorch2.6-manylinux-wheels/244/
`triton-3.2.0+rocm7.1.0.git20943800-cp313-cp313-linux_x86_64.whl pushed to http://compute-artifactory.amd.com/artifactory/compute-pytorch-rocm/compute-rocm-dkms-no-npi-hipclang/16516/triton_main_conditionalize/triton-3.2.0+rocm7.1.0.git20943800-cp313-cp313-linux_x86_64.whl`
=> [main] Conditionalize triton package name on rocm version

manywheel/Dockerfile_2_28
Fixes https://ontrack-internal.amd.com/browse/SWDEV-551662
Setuptools not found error 
We want to pin setuptools at 79.0.1 because upstream has pinned setuptools between 70 and 80. Brought in by https://github.com/pytorch/pytorch/pull/153052
In this rocm7.0 branch we are pinning via the dockerfile but in the main branch we will install requirements.txt before calling `python setup.py clean`
`setuptools>=70.1.0,<80.0  # setuptools develop deprecated on 80.0`
Validation: http://rocm-ci.amd.com/job/mainline-pytorch2.8-manylinux-wheels/104/
=> [DO NOT CHERRY PICK][rocm7.0]Fix setuptools

manywheel/Dockerfile_2_28, manywheel/build_torch_wheel.sh
Fixes https://ontrack-internal.amd.com/browse/SWDEV-551662
Setuptools not found error 
We want to pin setuptools at 79.0.1 because upstream has pinned setuptools between 70 and 80. Brought in by https://github.com/pytorch/pytorch/pull/153052
we will install requirements.txt before calling `python setup.py clean`
`setuptools>=70.1.0,<80.0  # setuptools develop deprecated on 80.0`
http://rocm-ci.amd.com/job/mainline-pytorch2.8-manylinux-wheels/110/
=> [main] install requirements.txt before setup.py
